connections:
  main:
    host: screeps.com
    password: <password>
    secure: true
    username: <username>
  ptr:
    host: screeps.com/ptr
    password: <password>
    secure: true
    username: <username>
max_history: 200000
max_scroll: 200000
smooth_scroll: true
